const W_KEYCODE = 87;
const A_KEYCODE = 65;
const S_KEYCODE = 83;
const D_KEYCODE = 68;

const UP_KEYCODE = 38;
const DOWN_KEYCODE = 40;
const LEFT_KEYCODE = 37;
const RIGHT_KEYCODE = 39;

const HEIGHT = 0.07;
const WIDTH = 0.5;
const LENGTH = 1;
const WHEELS = 0.1;
const ROTATION = 0.15;
const LEFT = 2.35;
const RIGHT = -0.85;
const UP = 0.8;

const KEY_CODES = {
	W_KEYCODE,
	A_KEYCODE,
	S_KEYCODE,
	D_KEYCODE,
	UP_KEYCODE,
	DOWN_KEYCODE,
	LEFT_KEYCODE,
	RIGHT_KEYCODE,
};

const SKATEBOARD = {
	HEIGHT,
	WIDTH,
	LENGTH,
	WHEELS,
	ROTATION,
	LEFT,
	RIGHT,
	UP,
};
export { KEY_CODES, SKATEBOARD };
